name: tower_defense_game
description: A fully documented and modular Tower Defense game built with Flutter and Flame engine.
publish_to: 'none'
version: 1.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: any
  flame: ^1.8.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  flame_tiled: ^1.13.0
  flutter_gen: ^5.10.0
  flutter_html: ^3.0.0
  intl: any
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/maps/
    - lib/l10n/